name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨2点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: malone6/freqtrade_strs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/ssssi/freqtrade_strs.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
